# Generated by Django 5.2.7 on 2026-06-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebida em')),
                ('read', models.BooleanField(default=False, verbose_name='lida')),
            ],
            options={
                'verbose_name': 'Mensagem de contato',
                'verbose_name_plural': 'Mensagens de contato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120, verbose_name='empresa')),
                ('role', models.CharField(max_length=120, verbose_name='cargo')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='local')),
                ('start_date', models.DateField(verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('description', models.TextField(verbose_name='descrição')),
                ('is_current', models.BooleanField(default=False, verbose_name='é o emprego atual')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Menor número aparece primeiro na linha do tempo.', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projetos/', verbose_name='imagem')),
                ('tags', models.CharField(blank=True, help_text='Separe as tags por vírgula. Ex: Python, Django, SQL', max_length=200, verbose_name='tags')),
                ('link', models.URLField(blank=True, verbose_name='link do projeto')),
                ('repo_link', models.URLField(blank=True, verbose_name='link do repositório')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('category', models.CharField(choices=[('linguagem', 'Linguagens & Frameworks'), ('dados', 'Dados & Automação'), ('ferramenta', 'Ferramentas')], default='linguagem', max_length=20, verbose_name='categoria')),
                ('proficiency', models.PositiveSmallIntegerField(default=3, help_text='Use um número de 1 a 5. É usado para desenhar a barrinha de nível.', verbose_name='proficiência (1 a 5)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
